# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - buoncibo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_05a1f0edceac4696b09371183c254a6d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0ae88364625c4f768a1dd2bed6f7bf32 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_05a1f0edceac4696b09371183c254a6d }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'buoncibo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1ec0339c08d0439488ed5100adb95a92 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_05a1f0edceac4696b09371183c254a6d }}/appsvc/wordpress-alpine-php:${{ github.sha }}'